version: "3"
services:
  gerenciador-despesa:
    image: gerenciador-despesa
    ports:
      - "8080:8080"
    networks:
      - rede-despesas
    depends_on:
      - mysqldb
      - zookeeper
      - kafka
      - analizador

  analizador:
    image: analizador
    ports:
      - "8081:8080"
    networks:
      - rede-despesas
    depends_on:
      - mysqldb
      - zookeeper
      - kafka

  mysqldb:
    image: mysql:8
    networks:
      - rede-despesas
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gerenciador
#
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - rede-despesas
    depends_on:
      - mysqldb
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - mysqldb
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - rede-despesas
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CREATE_TOPICS: CALCULAR_DESPESA
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  rede-despesas:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1

